"""DFIQ index: official snapshot (google/dfiq, pinned) + internal Q0xxx objects.

Both trees are loaded with the SAME parser (SPEC "Knowledge sources",
amendment A6): official data from ``knowledge/upstream/dfiq/dfiq/data``
(never baked into images - fetched by ``make update-knowledge`` on the host),
internal objects from ``knowledge/custom/dfiq/`` (authored in-repo,
generated by ``scripts/gen_internal_dfiq.py``).

Format note (journalized S1.5): at the pinned commit (DFIQ_COMMIT in
versions.env), the google/dfiq repository carries data in format v1.1.0
(``name`` + ``uuid`` + explicit ``internal`` flag + approaches embedded in
question files) while its own loader still parses the retired v1.0 format
(``display_name``) - neither the pinned PyPI package (1.0.1) nor the repo's
package code can load the pinned data. The loader therefore parses format
v1.1.0 directly, versioned against the data pin, with strict structural
validation - malformed files are a hard error, never a silent skip
(vocabulary discipline, SPEC knowledge rules).

``is_internal`` comes from the explicit ``internal`` flag when present and
from the DFIQ id convention ('0' in second position: Q0xxx/F0xxx/S0xxx) as
fallback; internal objects are never presented as official.

OS metadata is derived per component from the hunt catalogue seed: the union
of the ``os`` lists of the hunts whose ``dfiq:`` list contains the component
id. Missing sources degrade gracefully: the index reports what loaded, and
agents see an explicit note instead of a crash (a missing snapshot is a gap,
SPEC "Knowledge sources" rules).
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import yaml

from oreoa.vocab import OS

OFFICIAL_REL = Path("upstream") / "dfiq" / "dfiq" / "data"
CUSTOM_REL = Path("custom") / "dfiq"

_ID_PATTERNS = {
    "scenario": re.compile(r"^S\d{4}$"),
    "facet": re.compile(r"^F\d{4}$"),
    "question": re.compile(r"^Q\d{4}$"),
}
_UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
_DFIQ_VERSION_RE = re.compile(r"^\d{1,2}\.\d{1,2}\.\d{1,2}$")

_REQUIRED_FIELDS = {
    # `internal` is optional in practice: the pinned official data omits it on
    # scenario files (repo in a half-migrated state at the pin) - the id
    # convention ('0' in second position) is the fallback
    "scenario": ("id", "name", "uuid", "dfiq_version"),
    "facet": ("id", "name", "uuid", "dfiq_version", "parent_ids"),
    "question": ("id", "name", "uuid", "dfiq_version", "parent_ids"),
}

_HUNT_CATALOG_CANDIDATES = (
    "OREOA_HUNTS_CATALOG",  # compose mount (/hunts/hunts_catalog_seed.yaml)
    None,  # repo checkout fallback (host, tests)
)

INDEX_CACHE: dict[str, "DFIQIndex"] = {}


class Component:
    """One parsed DFIQ object (format v1.1.0)."""

    def __init__(self, data: dict, directory: Path, source: str):
        kind = data.get("type")
        if kind not in _ID_PATTERNS:
            raise ValueError(f"{directory.name}: unknown type {kind!r}")
        missing = [field for field in _REQUIRED_FIELDS[kind] if field not in data]
        if missing:
            raise ValueError(f"{directory / (data.get('id') or '?')}.yaml: missing fields {missing}")
        component_id = data["id"]
        if not _ID_PATTERNS[kind].fullmatch(component_id):
            raise ValueError(f"{component_id!r} does not match the DFIQ {kind} id pattern")
        if not _UUID_RE.fullmatch(str(data["uuid"])):
            raise ValueError(f"{component_id}: invalid uuid {data['uuid']!r}")
        if not _DFIQ_VERSION_RE.fullmatch(str(data["dfiq_version"])):
            raise ValueError(f"{component_id}: invalid dfiq_version {data['dfiq_version']!r}")
        parent_ids = data.get("parent_ids") or []
        if kind in ("facet", "question") and not parent_ids:
            raise ValueError(f"{component_id}: {kind} requires parent_ids")
        for parent in parent_ids:
            if kind == "facet" and not re.fullmatch(r"S\d{4}", str(parent)):
                raise ValueError(f"{component_id}: facet parent {parent!r} is not a scenario id")
            if kind == "question" and not re.fullmatch(r"F\d{4}", str(parent)):
                raise ValueError(f"{component_id}: question parent {parent!r} is not a facet id")
        self.id = component_id
        self.uuid = str(data["uuid"])
        self.name = str(data["name"]).rstrip()
        self.description = (data.get("description") or "").rstrip() or None
        self.tags = set(data.get("tags") or [])
        self.parent_ids = set(str(p) for p in parent_ids)
        self.type = kind
        self.dfiq_version = str(data["dfiq_version"])
        self.internal = bool(data.get("internal")) or component_id[1] == "0"
        self.source = source
        self.approaches = [
            {
                "name": approach.get("name"),
                "description": (approach.get("description") or "").strip(),
            }
            for approach in (data.get("approaches") or [])
            if isinstance(approach, dict)
        ]
        self.child_ids: set[str] = set()


def _parse_tree(data_path: Path, source: str) -> dict[str, Component]:
    """Parse one DFIQ tree (scenarios/facets/questions subdirectories)."""
    components: dict[str, Component] = {}
    for kind in ("scenario", "facet", "question"):
        directory = data_path / f"{kind}s"
        if not directory.is_dir():
            continue
        for yaml_file in sorted(directory.glob("*.yaml"), key=lambda p: p.name):
            if yaml_file.name.startswith("."):
                continue
            data = yaml.safe_load(yaml_file.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                raise ValueError(f"{yaml_file}: not a mapping")
            component = Component(data, directory, source)
            if component.id in components:
                raise ValueError(f"{component.id}: duplicate id in {data_path}")
            components[component.id] = component
    return components


def hunts_catalog_path() -> Path | None:
    """Locate the hunt catalogue seed (compose mount, then repo checkout)."""
    for var in _HUNT_CATALOG_CANDIDATES:
        if var:
            value = os.environ.get(var)
            if value and Path(value).is_file():
                return Path(value)
    fallback = Path(__file__).resolve().parents[2] / "hunts_catalog_seed.yaml"
    if fallback.is_file():
        return fallback
    return None


class DFIQIndex:
    """Read-only merged view over the official snapshot and internal objects."""

    def __init__(self, knowledge_root: Path | None = None):
        self.root = Path(knowledge_root or os.environ.get("OREOA_KNOWLEDGE", "/knowledge")).resolve()
        self._official = self._load_tree(self.root / OFFICIAL_REL, "official")
        self._internal = self._load_tree(self.root / CUSTOM_REL, "internal")
        self._hunts = self._load_hunt_catalog()
        self._os_by_component = self._derive_os()
        self._link_children()

    # -- loading ---------------------------------------------------------

    def _load_tree(self, data_path: Path, source: str) -> dict[str, Component] | None:
        """Load one DFIQ tree; returns None when the tree is absent."""
        if not (data_path / "questions").is_dir():
            return None
        return _parse_tree(data_path, source)

    def _load_hunt_catalog(self) -> dict[str, dict]:
        path = hunts_catalog_path()
        if path is None:
            return {}
        try:
            seed = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except OSError:
            return {}
        return {hunt["id"]: hunt for hunt in seed.get("hunts") or []}

    def _derive_os(self) -> dict[str, set[str]]:
        derived: dict[str, set[str]] = {}
        for hunt in self._hunts.values():
            hunt_os = {o for o in (hunt.get("os") or []) if o in OS}
            if not hunt_os:
                continue
            for component_id in hunt.get("dfiq") or []:
                derived.setdefault(component_id, set()).update(hunt_os)
        return derived

    def _link_children(self) -> None:
        for tree in (self._official, self._internal):
            if not tree:
                continue
            for component in tree.values():
                for parent_id in component.parent_ids:
                    # cross-tree edges (internal question under an official
                    # facet) resolve through the merged view
                    parent = self.get_component(parent_id)
                    if parent is not None:
                        parent.child_ids.add(component.id)

    # -- status ----------------------------------------------------------

    @property
    def official_available(self) -> bool:
        return self._official is not None

    @property
    def internal_available(self) -> bool:
        return self._internal is not None

    def status(self) -> dict:
        return {
            "official_snapshot": {
                "available": self.official_available,
                "path": str(self.root / OFFICIAL_REL),
                "note": "" if self.official_available else
                "missing - run make update-knowledge on the workstation",
            },
            "internal_objects": {
                "available": self.internal_available,
                "path": str(self.root / CUSTOM_REL),
            },
            "hunt_catalog": {
                "available": bool(self._hunts),
                "hunts": len(self._hunts),
            },
        }

    # -- queries ---------------------------------------------------------

    def get_component(self, component_id: str) -> Component | None:
        for tree in (self._official, self._internal):
            if tree and component_id in tree:
                return tree[component_id]
        return None

    def all_components(self) -> dict[str, Component]:
        merged: dict[str, Component] = {}
        if self._official:
            merged.update(self._official)
        if self._internal:
            merged.update(self._internal)
        return merged

    def component_os(self, component_id: str) -> list[str]:
        return sorted(self._os_by_component.get(component_id, set()))

    def answering_hunts(self, component_id: str) -> list[dict]:
        """Hunts whose seed ``dfiq:`` list contains the component id."""
        return [
            {
                "id": hunt_id,
                "title": hunt.get("title"),
                "os": hunt.get("os") or [],
            }
            for hunt_id, hunt in sorted(self._hunts.items())
            if component_id in (hunt.get("dfiq") or [])
        ]

    def list(
        self,
        component_type: str = "question",
        os_filter: str | None = None,
        internal: bool | None = None,
    ) -> list[dict]:
        """List components (sorted by id), optionally filtered by OS and
        internal flag. Official components carry ``is_internal: false``."""
        if component_type not in _ID_PATTERNS:
            raise ValueError(f"component_type {component_type!r} outside scenario|facet|question")
        if os_filter and os_filter not in OS:
            raise ValueError(f"os {os_filter!r} outside {OS}")
        selected: list[dict] = []
        for component in sorted(self.all_components().values(), key=lambda c: c.id):
            if component.type != component_type:
                continue
            if internal is not None and internal is not component.internal:
                continue
            entry = {
                "id": component.id,
                "display_name": component.name,
                "type": component_type,
                "is_internal": component.internal,
                "os": self.component_os(component.id),
            }
            if os_filter and os_filter not in entry["os"]:
                continue
            selected.append(entry)
        return selected

    def get(self, component_id: str) -> dict:
        component = self.get_component(component_id)
        if component is None:
            raise KeyError(f"unknown DFIQ id {component_id!r}")
        parents = []
        for parent_id in sorted(component.parent_ids):
            parent = self.get_component(parent_id)
            parents.append(
                {
                    "id": parent_id,
                    "display_name": parent.name if parent else None,
                    "is_internal": parent.internal if parent else parent_id[1] == "0",
                }
            )
        children = []
        for child_id in sorted(component.child_ids):
            child = self.get_component(child_id)
            children.append(
                {
                    "id": child_id,
                    "display_name": child.name if child else None,
                    "type": child.type if child else None,
                }
            )
        return {
            "id": component.id,
            "display_name": component.name,
            "type": component.type,
            "is_internal": component.internal,
            "description": component.description,
            "tags": sorted(component.tags),
            "parents": parents,
            "children": children,
            "os": self.component_os(component.id),
            "hunts": self.answering_hunts(component.id),
            "approaches": component.approaches,
            "dfiq_version": component.dfiq_version,
            "source": component.source,
        }

    def facets_of(self, question_id: str) -> list[str]:
        detail = self.get(question_id)
        return [parent["id"] for parent in detail["parents"] if parent["id"].startswith("F")]


def get_index(knowledge_root: Path | None = None) -> DFIQIndex:
    """Cached per knowledge root (the snapshot is read-only for the server)."""
    root = Path(knowledge_root or os.environ.get("OREOA_KNOWLEDGE", "/knowledge")).resolve()
    key = str(root)
    if key not in INDEX_CACHE:
        INDEX_CACHE[key] = DFIQIndex(root)
    return INDEX_CACHE[key]
